### ISSUE TITLE
Aggregated losses in scenario_risk

### ISSUE THREAD

**Issue by micheles** [gem/oq-risklib#375]
An user requested to add the functionality to export aggregated losses (i.e. portfolio losses) for each realization in the Scenario Risk Calculator. This would be similar to the loss tables of the Event Based Risk Calculator.

**Comment by raoanirudh** [comment]
Link to the request: https://groups.google.com/d/msg/openquake-users/cQWMeBrmPI8/AZZHKW3aJJ4J

**Comment by nickhorspool** [comment]
Just wondering if this has been implemented? If so, how do I export the values. Thanks.

**Comment by micheles** [comment]
No, this has not been implemented yet, since it has been deemed low priority.

**Comment by raoanirudh** [comment]
This issue was moved to gem/oq-engine#2321
