### ISSUE TITLE
Add csv exporters for the scenario_damage outputs

### ISSUE THREAD

**Issue by micheles** [gem/oq-risklib#405]
Now I have specs from Catalina and Anirudh, https://docs.google.com/spreadsheets/d/1XQzexMmlD4I_k5dgo-bnkalFD2nUVeNFsQhqVvH9rkA/edit?ts=560ba112#gid=535998355

**Comment by raoanirudh** [comment]
### Template for scenario ground motion fields

|   Longitude  |   Latitude  |  PGA_#0001  |  PGA_#0002  |  PGA_#0003  | … | SA(0.1)_#0001 | SA(0.1)_#0002 | SA(0.1)_#0003 | … |
|:------------:|:-----------:|:----------:|:----------:|:----------:|:-:|:------------:|:------------:|:------------:|:-:|
| -1.22570E+02 | 3.81130E+01 | 6.9481E-01 | 3.3424E-01 | 1.2495E-01 | … |  2.3295E-01  |  6.4395E-01  |  5.0039E-01  | … |
| -1.22114E+02 | 3.81130E+01 | 1.0090E-01 | 2.1241E-01 | 2.1322E-02 | … |  5.9193E-01  |  3.6746E-01  |  1.9361E-01  | … |
| -1.22000E+02 | 3.81130E+01 | 2.7647E-01 | 9.2468E-01 | 5.3349E-01 | … |  2.0677E-01  |  9.2979E-01  |  2.1163E-01  | … |
| -1.22000E+02 | 3.80000E+01 | 6.7521E-01 | 8.1728E-01 | 3.5368E-01 | … |  9.1544E-01  |  5.6278E-01  |  8.3956E-01  | … |
| -1.22000E+02 | 3.79100E+01 | 5.8284E-01 | 8.7594E-01 | 6.9020E-01 | … |  1.8499E-01  |  8.0060E-01  |  5.0044E-01  | … |
| -1.22000E+02 | 3.82250E+01 | 4.1964E-01 | 4.7037E-01 | 6.1432E-01 | … |  2.0335E-01  |  7.4245E-01  |  6.1753E-01  | … |
| -1.21886E+02 | 3.81130E+01 | 8.9685E-01 | 1.6730E-01 | 1.6314E-01 | … |  3.0965E-01  |  2.1864E-01  |  6.3308E-01  | … |
|       ⋮      |      ⋮      |      ⋮     |      ⋮     |      ⋮     | ⋱ |       ⋮      |       ⋮      |       ⋮      | ⋱ |

**Comment by raoanirudh** [comment]
### Template for scenario damage distribution per asset

| asset_ref | taxonomy |   longitude  |   latitude  | num_no_damage_mean | num_no_damage_std | num_ds1_mean | num_ds1_std | num_ds2_mean | num_ds2_std | num_ds3_mean | num_ds3_std | … |
|:---------:|:--------:|:------------:|:-----------:|:------------------:|:-----------------:|:------------:|:-----------:|:------------:|:-----------:|:------------:|:-----------:|:-:|
|     a1    | concrete | -1.22000E+02 | 3.81130E+01 |      3.210E+01     |     1.623E+01     |   0.000E+00  |  0.000E+00  |   0.000E+00  |  0.000E+00  |   0.000E+00  |  0.000E+00  | … |
|     a2    | concrete | -1.22114E+02 | 3.81130E+01 |      1.988E+01     |     1.126E+00     |   7.530E-02  |  7.158E-01  |   2.400E-02  |  2.378E-01  |   8.046E-03  |  8.304E-02  | … |
|     a3    |   steel  | -1.22570E+02 | 3.81130E+01 |      1.520E+01     |     2.570E+00     |   5.500E-01  |  1.640E+00  |   1.720E-01  |  5.370E-01  |   5.710E-02  |  1.870E-01  | … |
|     a4    |  masonry | -1.22000E+02 | 3.80000E+01 |      1.790E+01     |     1.010E+01     |   6.480E+00  |  5.070E+00  |   2.730E+00  |  2.410E+00  |   1.100E+00  |  1.140E+00  | … |
|     a5    |   adobe  | -1.22000E+02 | 3.79100E+01 |      1.568E+01     |     1.357E+01     |   8.773E+00  |  6.829E+00  |   3.681E+00  |  3.234E+00  |   1.480E+00  |  1.527E+00  | … |
|     a6    | concrete | -1.22000E+02 | 3.82250E+01 |      1.469E+01     |     1.806E+01     |   1.198E+01  |  9.007E+00  |   5.034E+00  |  4.320E+00  |   2.026E+00  |  2.055E+00  | … |
|     a7    |   wood   | -1.21886E+02 | 3.81130E+01 |      1.369E+01     |     2.255E+01     |   1.518E+01  |  1.118E+01  |   6.387E+00  |  5.406E+00  |   2.572E+00  |  2.584E+00  | … |
|     ⋮     |     ⋮    |       ⋮      |      ⋮      |          ⋮         |         ⋮         |       ⋮      |      ⋮      |       ⋮      |      ⋮      |       ⋮      |      ⋮      | ⋱ |

**Comment by raoanirudh** [comment]
### Template for scenario damage distribution map

| longitude | latitude | num_no_damage_mean | num_no_damage_std | num_ds1_mean | num_ds1_std | num_ds2_mean | num_ds2_std | num_ds3_mean | num_ds3_std | … |
|:---------:|:--------:|:------------------:|:-----------------:|:------------:|:-----------:|:------------:|:-----------:|:------------:|:-----------:|:-:|
| -122.5700 |  38.1130 |     2.5786E+00     |     7.7359E-01    |  2.4453E+00  |  7.3360E-01 |  1.4723E+00  |  4.4170E-01 |  8.3502E-01  |  2.5051E-01 | … |
| -122.1140 |  38.1130 |     7.5638E+00     |     2.2691E+00    |  4.4863E-01  |  1.3459E-01 |  1.3285E+00  |  3.9855E-01 |  1.9574E-01  |  5.8722E-02 | … |
| -122.0000 |  37.9100 |     9.5219E+00     |     2.8566E+00    |  5.8399E+00  |  1.7520E+00 |  6.5776E-01  |  1.9733E-01 |  6.4037E-02  |  1.9211E-02 | … |
| -122.0000 |  38.0000 |     9.2736E+00     |     2.7821E+00    |  3.3416E-01  |  1.0025E-01 |  1.3468E+00  |  4.0405E-01 |  1.8287E-01  |  5.4860E-02 | … |
| -122.0000 |  38.1130 |     4.3008E+00     |     1.2903E+00    |  5.1041E+00  |  1.5312E+00 |  1.7123E+00  |  5.1368E-01 |  1.0359E+00  |  3.1078E-01 | … |
| -122.0000 |  38.2250 |     6.7834E+00     |     2.0350E+00    |  3.8845E+00  |  1.1653E+00 |  2.2052E+00  |  6.6156E-01 |  1.1722E+00  |  3.5167E-01 | … |
| -121.8860 |  38.1130 |     9.4751E+00     |     2.8425E+00    |  3.2242E+00  |  9.6725E-01 |  1.2234E+00  |  3.6703E-01 |  7.8188E-01  |  2.3456E-01 | … |
|     ⋮     |     ⋮    |          ⋮         |         ⋮         |       ⋮      |      ⋮      |       ⋮      |      ⋮      |       ⋮      |      ⋮      | ⋱ |

**Comment by raoanirudh** [comment]
### Template for damage distribution per taxonomy

| taxonomy | num_no_damage_mean | num_no_damage_std | num_ds1_mean | num_ds1_std | num_ds2_mean | num_ds2_std | num_ds3_mean | num_ds3_std | … |
|:--------:|:------------------:|:-----------------:|:------------:|:-----------:|:------------:|:-----------:|:------------:|:-----------:|:-:|
|   tax_1  |      6.912E+01     |     1.590E+01     |   2.124E+01  |  4.884E+00  |   9.241E+00  |  2.125E+00  |   0.000E+00  |  0.000E+00  | … |
|   tax_2  |      1.430E+02     |     3.289E+01     |   3.524E+01  |  8.104E+00  |   1.212E+01  |  2.789E+00  |   2.123E+00  |  4.883E-01  | … |
|     ⋮    |          ⋮         |         ⋮         |       ⋮      |      ⋮      |       ⋮      |      ⋮      |       ⋮      |      ⋮      | … |
|   tax_n  |      9.824E+01     |     2.260E+01     |   1.312E+01  |  3.019E+00  |   6.387E+00  |  1.469E+00  |   2.572E+00  |  5.916E-01  | … |

**Comment by CatalinaYepes** [comment]
I think the ground motion fields should be exported separately for each imt.

**Comment by raoanirudh** [comment]
Updated my comments above to include suggestions for file paths and names for the exported files.

**Comment by raoanirudh** [comment]
Currently, collapse maps are produced for all loss types, including `contents` and `business_interruption`.  However, the collapse map is a meaningful output only for `structural` damage calculations, and only in calculations where the ultimate limit state defined in the structural fragility model indeed corresponds to collapse.

An alternative approach could be to include the lon, lat coordinates for each asset directly in the asset damage distribution output file, thus avoiding the need to produce a separate "collapse map".

**Comment by CatalinaYepes** [comment]
The main idea of the "collapse map" is to identify the assets at the same location.
One alternative could be to removed the "collapse map" from the oq outputs and add instead a "site id" in the gmf and in the damage per asset in the proposed tables.

**Comment by micheles** [comment]
Some notes:

1. for scenario ground motion fields the implemented exporter produces one file per each IMT, as Catalina wants
2. for scenario damage distribution per asset the implemented exporter produces a single file for all loss types; this has a big advantage when comparing files with tools like diff or meld, since there a lot less files to compare; moreover, since the calculator manages all the loss types at the same time, this is the most natural way to proceed and Anirudh approved it.
3. there is no exporter for the scenario damage distribution map since it can be trivially obtained from the scenario damage distribution per asset file by aggregating the assets on the same location; notice that the assets are ordered first by location and then lexycographically by asset_ref
4. for scenario damage distribution per taxonomy the implemented exporter produces a single file collecting all loss types, like for the scenario damage distribution per asset
5. there is also an exporter for the total damage distribution, producing a single file with all loss types
