### ISSUE TITLE
If there is a ConsequenceModel for loss type X, all the assets must have a value for loss type X

### ISSUE THREAD

**Issue by micheles** [gem/oq-risklib#420]
Otherwise the computation must be stopped. The check should be done in the pre-execute phase, before starting the real computation. An error like we have in scenario_risk is fine:

```ValueError: node costs: Invalid Exposure. Missing cost set(['nonstructural']) for asset a1```

**Comment by raoanirudh** [comment]
Similarly, if there is a consequence model for loss type '**occupants**', all assets must include the number of occupants (for at least one period of the day).

Ideally, the same check for occupants should also be performed in scenario_risk if an occupants vulnerability model is provided.
