### ISSUE TITLE
Put oq-risklib under Travis control

### ISSUE THREAD

**Issue by micheles** [gem/oq-risklib#425]
This is more convenient than using Jenkins, also because Travis can run the tests against different Python versions. Jenkins would still be used, but only to run the demos, not the tests. The dependency from hazardlib can be managed with a simple `pip install https://github.com/gem/oq-hazardlib/archive/master.zip`.

**Comment by daniviga** [comment]
We should investigate a way to get the dependency (hazardlib) from the same branch as risklib (if exists) otherwise testing branches will be difficult

**Comment by micheles** [comment]
For the moment Travis will only with hazardlib master. Since I do not plan to remove the tests on Jenkins (but by default they should be disabled) if we need to run a cross branch check we will run it on Jenkins.
In the future I plan to merge oq-hazardlib and oq-risklib into a single repository oq-lite.
