### ISSUE TITLE
Change the risk CSV exports by following the document of Catalina and Anirudh

### ISSUE THREAD

**Issue by micheles** [gem/oq-risklib#463]
https://docs.google.com/spreadsheets/d/1XQzexMmlD4I_k5dgo-bnkalFD2nUVeNFsQhqVvH9rkA/edit?ts=560ba112#gid=369943397

**Comment by raoanirudh** [comment]
### Template for scenario losses per asset

---

File path and name:

if single gsim: **_`export_dir`/losses-`loss_type`.csv_**
else: **_`export_dir`/`gsim_name`/losses-`loss_type`.csv_**

---

| asset_ref | taxonomy | longitude    | latitude    | mean_loss | stddev_loss | mean_insured_loss | stddev_insured_loss |
|-----------|----------|--------------|-------------|-----------|-------------|-------------------|---------------------|
| a1        | concrete | -1.22000E+02 | 3.81130E+01 | 3.210E+01 | 2.100E+01   | 1.926E+01         | 1.260E+01           |
| a2        | concrete | -1.22114E+02 | 3.81130E+01 | 1.988E+01 | 1.212E+01   | 1.193E+01         | 7.274E+00           |
| a3        | steel    | -1.22570E+02 | 3.81130E+01 | 1.520E+01 | 1.934E+01   | 9.120E+00         | 1.160E+01           |
| a4        | masonry  | -1.22000E+02 | 3.80000E+01 | 3.537E+01 | 2.314E+01   | 2.122E+01         | 1.389E+01           |
| a5        | adobe    | -1.22000E+02 | 3.79100E+01 | 2.191E+01 | 1.336E+01   | 1.315E+01         | 8.016E+00           |
| a6        | concrete | -1.22000E+02 | 3.82250E+01 | 1.675E+01 | 2.131E+01   | 1.005E+01         | 1.279E+01           |
| a7        | wood     | -1.21886E+02 | 3.81130E+01 | 3.898E+01 | 2.550E+01   | 2.339E+01         | 1.530E+01           |
| ⋮         | ⋮        | ⋮            | ⋮           | ⋮         | ⋮           | ⋮                 | ⋮                   |

---

**Comment**: If insured losses are not computed, the last two columns in the table should be skipped.

**Comment by raoanirudh** [comment]
### Template for scenario loss map

---

File path and name:

if single gsim: **_`export_dir`/loss-map-`loss_type`.csv_**
else: **_`export_dir`/`gsim_name`/loss-map-`loss_type`.csv_**

---

|   longitude  |   latitude  | mean_loss | stddev_loss | mean_insured_loss | stddev_insured_loss |
|:------------:|:-----------:|:---------:|:-----------:|:-----------------:|:-------------------:|
| -1.22000E+02 | 3.81130E+01 | 1.284E+02 |  8.400E+01  |     7.704E+01     |      5.040E+01      |
| -1.22114E+02 | 3.81130E+01 | 7.953E+01 |  4.849E+01  |     4.772E+01     |      2.910E+01      |
| -1.22570E+02 | 3.81130E+01 | 6.080E+01 |  7.737E+01  |     3.648E+01     |      4.642E+01      |
| -1.22000E+02 | 3.80000E+01 | 1.415E+02 |  9.257E+01  |     8.490E+01     |      5.554E+01      |
| -1.22000E+02 | 3.79100E+01 | 8.765E+01 |  5.344E+01  |     5.259E+01     |      3.206E+01      |
| -1.22000E+02 | 3.82250E+01 | 6.700E+01 |  8.526E+01  |     4.020E+01     |      5.115E+01      |
| -1.21886E+02 | 3.81130E+01 | 1.559E+02 |  1.020E+02  |     9.356E+01     |      6.121E+01      |
|       ⋮      |      ⋮      |     ⋮     |      ⋮      |         ⋮         |          ⋮          |

---

**Comment**: If insured losses are not computed, the last two columns in the table should be skipped.

**Comment by raoanirudh** [comment]
### Template for scenario loss per taxonomy

---

File path and name:

if single gsim: **_`export_dir`/losses-taxonomy-`loss_type`.csv_**
else: **_`export_dir`/`gsim_name`/losses-taxonomy-`loss_type`.csv_**

---

| taxonomy | mean_loss | stddev_loss | mean_insured_loss | stddev_insured_loss |
|:--------:|:---------:|:-----------:|:-----------------:|:-------------------:|
|   adobe  | 2.449E+06 |  1.602E+06  |     1.470E+06     |      9.614E+05      |
| concrete | 1.517E+06 |  9.250E+05  |     9.103E+05     |      5.550E+05      |
|  masonry | 1.160E+06 |  1.476E+06  |     6.959E+05     |      8.854E+05      |
|   steel  | 2.699E+06 |  1.766E+06  |     1.619E+06     |      1.059E+06      |
|   wood   | 1.672E+06 |  1.019E+06  |     1.003E+06     |      6.116E+05      |
|     ⋮    |     ⋮     |      ⋮      |         ⋮         |          ⋮          |

---

**Comment**: If insured losses are not computed, the last two columns in the table should be skipped.

**Comment by CatalinaYepes** [comment]
In the 'Template for scenario loss per taxonomy', at the end the total losses should be included

**Comment by micheles** [comment]
The scenario loss map can be obtained by aggregating the scenario losses per asset. I am not producing it: the aggregation can be done in the plotting tool.

**Comment by micheles** [comment]
The missing piece now is `losses_by_taxonomy` for scenario_risk.
