### ISSUE TITLE
Float comparison issue when reading a GMF file

### ISSUE THREAD

**Issue by raoanirudh** [gem/oq-risklib#546]
When reading pre-computed ground motion fields from an xml file, in some cases (such as for the file shown below), the comparison `if (node['lon'], node['lat']) != (lon, lat)` ([readinput.py:L1021](https://github.com/gem/oq-risklib/blob/master/openquake/commonlib/readinput.py#L1021)) fails and the '*The site mesh is not ordered*' error is raised, even though the sites in the gmf file are ordered correctly.

```xml
<?xml version="1.0" encoding="utf-8"?>
<nrml xmlns="http://openquake.org/xmlns/nrml/0.4"
      xmlns:gml="http://www.opengis.net/gml">

<gmfCollection gsimTreePath="" sourceModelTreePath="">
  <gmfSet stochasticEventSetId="1">
    <gmf IMT="PGA" ruptureId="scenario-0">
      <node gmv="0.0124783118478" lat="43.58248037" lon="12.1244171"/>
      <node gmv="0.0126515007046" lat="43.58217888" lon="12.12477995"/>
      <node gmv="0.0124056290492" lat="43.58120146" lon="12.12478193"/>
    </gmf>
  </gmfSet>
</gmfCollection>

</nrml>
```

```sh
$ (node['lon'], node['lat'])
$ (12.12478, 43.58218)

$ (lon, lat)
$ (12.124779999999999, 43.581200000000003)

$ (node['lon'], node['lat']) != (lon, lat)
$ True
```

**Comment by micheles** [comment]
The problem is with the coordinates `(12.12477995, 43.58217888), (12.12478193, 43.58120146)`. When rounded to the 5th digit they become `(12.12478, 43.58218), (12.12478, 43.58120)` and the ordering change :-(
