### ISSUE TITLE
Check if psutil 3 is supported

### ISSUE THREAD

**Issue by daniviga** [gem/oq-risklib#650]
We should check if OQ works fine with psutil 3 or the API is changed and the code needs to be adapted (like we did from 12.04 to 14.04).

**Comment by micheles** [comment]
I checked this some time ago and the code needs to be adapted, but it should be pretty easy.

**Comment by daniviga** [comment]
psutil 3.0 seems to work fine with the current code apart from this test https://github.com/gem/oq-risklib/blob/master/openquake/commonlib/tests/writers_test.py#L87 where we make a direct call to an old API instead of filtering by version.
