### ISSUE TITLE
Seven minor bugs

### ISSUE THREAD

**Issue by micheles** [gem/oq-risklib#674]
The following were reported by Anirudh and Cata and are not blocking for the release 1.8:

- [x] risk calculations which use a combined job file do not appear in the list
  of risk calculations printed by oq-engine --lrc

- [x] loss curve and loss map xml output files must also include
      the risk investigation time

- [x] “tag:|S100” in the header line of exported event loss tables should
      be changed to rupture_tag (or rupture_id to match the terminology
      used in the SES file)

- [x] “asset_ref:|S20” in the header line of exported csv avg_losses in event_based_risk, damages-rlzs in classical_damage, loss_curves and loss_maps in classical_risk and event_based_risk, and csq_by_asset in scenario_damage should be changed to asset_ref

- [x] "taxonomy:|S100" in the header line of exported csq_by_taxon should be changed to taxonomy

**Comment by raoanirudh** [comment]
6. “asset_ref:|S20” in the header line of exported csv avg_losses in event_based_risk, damages-rlzs in classical_damage, loss_curves and loss_maps in classical_risk and event_based_risk, and csq_by_asset in scenario_damage should be changed to asset_ref

7. "taxonomy:|S100" in the header line of exported csq_by_taxon should be changed to taxonomy

**Comment by micheles** [comment]
Issue #1 has been solved in https://github.com/gem/oq-engine/pull/1937

**Comment by micheles** [comment]
The issue about the CSV headers has been solved in https://github.com/gem/oq-risklib/pull/696

**Comment by micheles** [comment]
Issue 2 has been implemented in https://github.com/gem/oq-risklib/pull/697
