### ISSUE TITLE
Issues with csv outputs in ScenarioRisk 

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-risklib#709]
1. The output `losses_by_taxo` is missing

2. The aggregated losses should be exported in a single file (currently one file per loss_type). The idea is to be consistent with the output `losses_by_asset` (currently called avg_losses), in which columns have the mean and std dev. for each loss_type

3. All output names should be modified (except the gmf)

**Comment by micheles** [comment]
1. I am not adding an output `losses_by_taxo`: if it is really needed, please open a new ticket and it will be added after the release engine 2.0.

2. The aggregate losses are now exported in a single file. The columns are mean, stddev and unit for each loss type.

3. The output names have been modified and now contain the realization ordinal.
