### ISSUE TITLE
hazard_maps =false and uniform_hazard_spectra = true makes no sense

### ISSUE THREAD

**Issue by micheles** [gem/oq-risklib#740]
This happened to Yen-Shin: probably we should generate the hazard_maps if uniform_hazard_spectra is True in any case (perhaps with a warning).

**Comment by g-weatherill** [comment]
For a single site or a small number of sites it actually makes perfect sense that the user wishes to view the uniform hazard spectra but has no interest in the maps. Ultimately the internal calculation to get the IMLs for the required PoE is the same but there is no reason to store or export the maps in this case.

**Comment by micheles** [comment]
Technically right now the UHS can be computed only if the hazard maps are available in the datastore. Users  keep getting confused (see https://groups.google.com/d/msg/openquake-users/zCW7gypguiQ/ApceZbeEBgAJ). The solution I see is to compute the hazard maps if  uniform_hazard_spectra is True if hazard_maps is not specified.
