### ISSUE TITLE
Permit the use of the "." and "|" characters in the source IDs

### ISSUE THREAD

**Issue by g-weatherill** [gem/oq-risklib#753]
In implementing the US National Seismic Hazard map for the gridded seismicity source there is nothing to uniquely identify a point besides its location. In this case it can be useful to have the ID as the location string (e.g. `10.0N_31.0E`) or as a join of several variables based on conditions. The "." and "|" characters would allow some flexibility in the representation

**Comment by micheles** [comment]
Do we really need the '|' character? In the past it gave us problems since it is not a valid characters for Windows filenames. That means that it would be impossible to save data about the source in a file with the same name as the source on Windows in presence of a '|'.

**Comment by g-weatherill** [comment]
Probably it is not critical to have the "|". What about an alternative separator (e.g. "~")?

**Comment by micheles** [comment]
'~' is no good since it is already used in the tags of the event based calculator. The following characters cannot be used in Windows filenames (see https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx):

```
< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)
```
Not much is left. But we already have `_` (underscore) so I think we can just drop `|`.

**Comment by g-weatherill** [comment]
OK, then we can stick with the underscore. Are spaces acceptable?

**Comment by micheles** [comment]
Yes, spaces are acceptable.
