### ISSUE TITLE
Problems with exporters for Event-Based statistics 

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-risklib#813]
The Event-Based calculations for SARA in wilson (calc_ids from 9963 to 9969) had in the job.ini the option `avg_losses = true`.

However, the outputs for `avg_losses-stats` and `agg_losses-stats` are not available.

Reference to issue #681

**Comment by micheles** [comment]
We discussed with Anirudh a strategy to compute `agg_losses-stats` (for instance by considering only the events common to all realizations) but at the end decided to postpone this.
